package edu.ohsu.cmp.logservice.security;

import edu.ohsu.cmp.logservice.Constants;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import org.apache.commons.lang3.StringUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpMethod;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Component;
import org.springframework.web.servlet.HandlerInterceptor;

import java.util.regex.Pattern;

@Component
public class AuthorizationInterceptor implements HandlerInterceptor {
    private static final String BEARER_PREFIX = "Bearer ";
    private static final Pattern AUTHORIZATION_PATTERN = Pattern.compile("^" + BEARER_PREFIX + "[a-zA-Z0-9-]+$");

    private final Logger logger = LoggerFactory.getLogger(this.getClass());

    @Autowired
    private SecurityConfig security;

    @Override
    public boolean preHandle(HttpServletRequest request, HttpServletResponse response, Object handler) throws Exception {
        if (request.getMethod().equals(HttpMethod.OPTIONS.name())) {
            // permit OPTIONS calls to go through unimpeded.  these are used for CORS preflight and are generated by
            // the browser, it's unrealistic to try to set the Authorization header on these calls
            return true;

        } else if (StringUtils.equals(request.getServletPath(), "/") ||StringUtils.equals(request.getServletPath(), "/status")) {
            // this is the only endpoint that doesn't require authorization
            return true;
        }

        String authorization = request.getHeader(HttpHeaders.AUTHORIZATION);
        if (StringUtils.isBlank(authorization)) {
            logger.debug("Missing Authorization header from {}", request.getRemoteAddr());
            response.setStatus(HttpStatus.UNAUTHORIZED.value());
            return false;
        }

        String authorizedClientAppName = null;
        if (AUTHORIZATION_PATTERN.matcher(authorization).matches()) {
            String clientToken = authorization.substring(BEARER_PREFIX.length());
            authorizedClientAppName = security.getAuthorizedClientAppName(clientToken);
        }

        if (authorizedClientAppName != null) {
            logger.info("OK : {} from {}", authorizedClientAppName, request.getRemoteAddr());
            request.setAttribute(Constants.CLIENT_APP_NAME_ATTRIBUTE, authorizedClientAppName);
            return true;

        } else {
            logger.warn("Unauthorized : from {}", request.getRemoteAddr());
            response.setStatus(HttpStatus.UNAUTHORIZED.value());
            return false;
        }
    }
}
