package edu.ohsu.cmp.logservice.security;

import edu.ohsu.cmp.logservice.Constants;
import io.micrometer.common.util.StringUtils;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpMethod;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Component;
import org.springframework.web.servlet.HandlerInterceptor;

@Component
public class AuthorizationInterceptor implements HandlerInterceptor {
    private static final String BEARER_PREFIX = "Bearer ";

    private final Logger logger = LoggerFactory.getLogger(this.getClass());

    @Autowired
    private SecurityConfig security;

    @Override
    public boolean preHandle(HttpServletRequest request, HttpServletResponse response, Object handler) throws Exception {
        String authorizedClientAppName = null;

        if (request.getMethod().equals(HttpMethod.OPTIONS.name())) {
            // permit OPTIONS calls to go through unimpeded.  these are used for CORS preflight and are generated by
            // the browser, it's unrealistic to try to set the Authorization header on these calls
            return true;
        }

        String authorization = request.getHeader(HttpHeaders.AUTHORIZATION);
        if (StringUtils.isNotBlank(authorization)) {
            if (authorization.startsWith(BEARER_PREFIX)) {
                String clientToken = authorization.substring(BEARER_PREFIX.length());
                authorizedClientAppName = security.getAuthorizedClientAppName(clientToken);
            }
        }

        if (authorizedClientAppName != null) {
            logger.info("OK : {} from {}", authorizedClientAppName, request.getRemoteAddr());
            request.setAttribute(Constants.CLIENT_APP_NAME_ATTRIBUTE, authorizedClientAppName);
            return true;

        } else {
            logger.warn("Unauthorized : {} from {}", authorization, request.getRemoteAddr());
            response.setStatus(HttpStatus.UNAUTHORIZED.value());
            return false;
        }
    }
}
